Development
suretrust/mint-sign-in-page pull request #1
Opened 2019-02-25 13:35 UTC by suretrust

Submitting for code review.

2019-02-25 20:19 UTC, inhaq requested changes
### Great work on this project 🏆
Kindly look into these changes mentioned below. 
You can improve this project by adding the logo of Intuit as well.
In order to see whether your HTML is good, you can validate it [here](https://validator.w3.org). Once you finished with the changes and improvements, kindly resubmit it and mentioned me(Inzimam) in reviewed before. Happy coding!

2019-02-25 20:19 UTC, inhaq commented on css/style.css
> +    font-family: 'Open Sans', Arial, sans-serif;
Good work on adding `font-family` but you'll need to add `link` in HTML as well for the font. Check out [Google fonts](https://fonts.google.com/specimen/Open+Sans).

2019-02-25 20:19 UTC, inhaq commented on css/style.css
> +#signup section {
Consider looking into [this resource](https://css-tricks.com/the-difference-between-id-and-class/) in order to learn more about CSS class and id. Kindly figure out what you are doing wrong here.
Hint: Problem is with selectors on line 7 and 15.

2019-02-25 20:19 UTC, inhaq commented on css/style.css
> +button {
Instead of using HTML tags directly, I would recommend using classes.

2019-02-25 20:19 UTC, inhaq commented on index.html
> +                <center>
The `center` element is obsolete. Use CSS instead.

2019-02-25 20:19 UTC, inhaq commented on index.html
> +                    <center>
The `center` element is obsolete. Use CSS instead.

2019-02-25 20:19 UTC, inhaq commented on css/style.css
> +    background-image: url("../img/locked.png"), linear-gradient(to bottom,#167CCC 0,#0077C5 100%);
Use `./img/locked.png` instead. Remove first dot as it means to go to the previous directory.

2019-02-25 20:19 UTC, inhaq commented on css/style.css
> +    background-image: url("../img/unlocked.png");
Use `./img/unlocked.png` instead. Remove first dot as it means to go to the previous directory.

2019-02-26 16:14 UTC, suretrust commented on css/style.css
> +    background-image: url("../img/locked.png"), linear-gradient(to bottom,#167CCC 0,#0077C5 100%);
We pointed it there because that's where the file we need is.

2019-02-26 19:33 UTC, inhaq commented
### Congrats 🎉 on completing this project
Feel free to submit a project completion form for this project, it's 👍🏻.
Suggestion: Don't use ID in CSS as selectors in the next projects. Happy Coding 😊

2019-02-27 09:47 UTC, merged